### ISSUE TITLE
Update MPI Hello for Shifter & Singularity sections

### ISSUE THREAD

**Issue by ajyounge** [supercontainers/sc19-tutorial#5]
In our tutorial, we should have users leverage an ECP base image to build first mpi-hello. This will help reinforce some best practices with using supported base images. Need to first develop this base image and push it to Dockerhub (based on Shane's NERSC image?)

**Comment by ajyounge** [comment]
Can we used Sameer's minimal image he built recently with UBI8 and a minimal spack environment?

@sameershende @ArangoGutierrez

**Comment by ArangoGutierrez** [comment]
I can for sure, image reference link @sameershende  @ajyounge ?

**Comment by ajyounge** [comment]
Using nersc image, closing.
