### ISSUE TITLE
Injest Feedback

### ISSUE THREAD

**Issue by ajyounge** [supercontainers/sc19-tutorial#7]
Should should we encourage feedback on the tutorial from participants? Github issues? SC usage?

**Comment by sameershende** [comment]
Summary of Reviews of tut148s1: Getting Started with Containers on HPC at ISC-HPC 2019.


[ISC19_Containers_evaluations.pdf](https://github.com/supercontainers/sc19-tutorial/files/3740392/ISC19_Containers_evaluations.pdf)
[Reviews_ISC-HPC19_tutorial_submission.pdf](https://github.com/supercontainers/sc19-tutorial/files/3740394/Reviews_ISC-HPC19_tutorial_submission.pdf)

**Comment by ArangoGutierrez** [comment]
++

**Comment by ajyounge** [comment]
Marking closed, think we're in the process of doing this.
